import type { Metadata } from "next";
import { ReactNode } from "react";
import "./globals.css";
import Wallet  from "./components/WalletProvider"; 



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Wallet>
          {children}
        </Wallet>
      </body>
    </html>
  );
}